import type { DivisionPayRatesRow } from "@shared/types";

const pct = (row: Omit<DivisionPayRatesRow, "assigning_fee">): DivisionPayRatesRow => ({
  ...row,
  assigning_fee: { amount: 10, mode: "percent" },
});

/** HNB Senior division rates from association pay matrix (sample values). */
export const HNB_SENIOR_PAY_RATES_TEMPLATE: Record<string, DivisionPayRatesRow> = {
  "Atlantic University Sport": pct({
    REF1: 185,
    REF2: 185,
    LINE1: 125,
    LINE2: 125,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Atlantic University Sport Female": pct({
    REF1: 185,
    REF2: 185,
    LINE1: 125,
    LINE2: 125,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Maritime Jr. A": pct({
    REF1: 130,
    REF2: 130,
    LINE1: 90,
    LINE2: 90,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: true,
  }),
  "New Brunswick Jr. B": pct({
    REF1: 110,
    REF2: 110,
    LINE1: 75,
    LINE2: 75,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "NB/PEI Major U18 AAA": pct({
    REF1: 120,
    REF2: 120,
    LINE1: 85,
    LINE2: 85,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Eastern Conference High School Hockey": pct({
    REF1: 95,
    REF2: 95,
    LINE1: 65,
    LINE2: 65,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Beausejour Senior Hockey League": pct({
    REF1: 85,
    REF2: 85,
    LINE1: 60,
    LINE2: 60,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "AHG U18AAA": pct({
    REF1: 120,
    REF2: 120,
    LINE1: 85,
    LINE2: 85,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Atlantic Hockey Group - Adult Divisions 1 2 & 3": pct({
    REF1: 37,
    REF2: 0,
    LINE1: 26.5,
    LINE2: 26.5,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Parkton Hockey League": pct({
    REF1: 55,
    REF2: 55,
    LINE1: 40,
    LINE2: 40,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
  "Monctonian U18 AAA Tournament": pct({
    REF1: 120,
    REF2: 120,
    LINE1: 85,
    LINE2: 85,
    SUPERVISOR: 0,
    TIMEKEEPER: 0,
    travel_pay_enabled: false,
    cash_games_default: false,
  }),
};
